services:
  tomcat:
    build: .
    container_name: usermanagement-tomcat
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
