services:
  app:
    build: .
    container_name: user_app
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:mysql://db:3306/user_management
      - DB_USER=root
      - DB_PASSWORD=root
      - HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_management
    ports:
      - "3307:3306"
